name: Test

permissions:
  contents: read
  issues: write

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

    # 2. Build project image
      - name: Build project image
        run: bash build.sh

    # 3. Create test network
      - name: Create Test network
        run: podman network create bna-test-net
    # 4. Launch test db
      - name: Launch test db
        run: bash testdb.sh

    # 5. Run tests
      - name: Run tests inside container
        id: run_tests
        run: |
          mkdir -p artifacts

          bash test.sh
          bash lint.sh

    # 6. Combine outputs into single report
      - name: Combine outputs into single report
        run: |
          echo "---" >> artifacts/combined_report.md
          echo "title: Automated report" >> artifacts/combined_report.md
          echo "---" >> artifacts/combined_report.md
          echo "POTATO" >> artifacts/combined_report.md
          echo "## Pytest Results" > artifacts/combined_report1.md
          echo "```" >> artifacts/combined_report1.md
          cat artifacts/pytest_output.txt >> artifacts/combined_report1.md
          echo "```" >> artifacts/combined_report1.md
          echo "---" >> artifacts/combined_report1.md
          echo "## Pylint Results" >> artifacts/combined_report1.md
          echo "```" >> artifacts/combined_report1.md
          cat artifacts/pylint_output.txt >> artifacts/combined_report1.md
          echo "```" >> artifacts/combined_report1.md

    # 7. Create github issue with results
      - name: Create github issues with results
        if: always()
        uses: JasonEtco/create-an-issue@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: artifacts/combined_report.md
